// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brfjckruhdbkalskqmai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZmpja3J1aGRia2Fsc2txbWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mjk1MDAsImV4cCI6MjA3MTEwNTUwMH0.s66hFzyJXOcexDiOb3aZ7iR8rvbIjNIxq5kWBK0z6CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});